=== [미구현] 영화인 목록

operation::find-makers[snippets='http-request,http-response,response-fields']

=== [미구현] 영화인 상세조회

operation::find-maker[snippets='http-request,path-parameters,http-response,response-fields']

=== [미구현] 영화인 정보 수정

operation::modify-maker[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== [미구현] 영화인과의 대화 목록

operation::find-qnas[snippets='http-request,path-parameters,response-fields']

=== [미구현] 영화인과의 대화 등록

operation::append-qna[snippets='http-request,path-parameters,request-fields,response-fields']

=== [미구현] 영화인과의 대화 수정

operation::modify-qna[snippets='http-request,path-parameters,request-fields,response-fields']

=== [미구현] 영화인과의 대화 삭제

operation::delete-qna[snippets='http-request,path-parameters,response-fields']

=== [미구현] 영화인과의 대화 댓글 등록

operation::append-comment[snippets='http-request,path-parameters,request-fields,response-fields']

=== [미구현] 영화인과의 대화 댓글 수정

operation::modify-comment[snippets='http-request,path-parameters,request-fields,response-fields']